FROM registry.centos.org/che-stacks/spring-boot

MAINTAINER <cloudtogo.cn>

COPY linux_amd64/terminal /mnt/che/terminal
COPY linux_amd64/exec /mnt/che/exec-agent
COPY ws-agent.tar.gz /mnt/che/ws-agent.tar.gz
